### ISSUE TITLE
plotFour & plotSDLogQ errors

### ISSUE THREAD

**Issue by tungmilan** [USGS-R/EGRET#143]
Hello,

I tried `plotFour` & `plotSDLogQ` for my data but got the following errors

```
Error in seq.default(startDec, endDec - window, 0.1) : 
  wrong sign in 'by' argument
```

How should I fix this? Thank you!

**Sample R code:**

```
startDate <- '2007-10-01'
endDate <- '2017-09-30'
station_code <- "12488500"
data_code <- "00060"
dat <- readNWISDaily(station_code, data_code, startDate, endDate)
INFO <- readNWISInfo(station_code, data_code)
eList <- as.egret(INFO, dat , NA, NA)

#### Check flow history data: 
plotFourStats(eList,  qUnit  = 1)
plotSDLogQ(eList)
plotFour(eList, qUnit = 1)

```

**Comment by ldecicco-USGS** [comment]
Since you don't have that long of a period of record, you'll need to adjust the default value for the "window" in the `plotSDLogQ` function. For example, you could run:

```r
plotSDLogQ(eList, window = 7)
plotFour(eList, qUnit = 1, window = 7)
```
The default value for the window argument is 15:
"numeric which is the full width, in years, of the time window over which the standard deviation is computed, default = 15"

I will make a note though to create a more helpful error message!

**Comment by tungmilan** [comment]
Thanks @ldecicco-USGS for the fix! Would it be better to let the function chose the default value dynamically based on the length of the data? If the length is smaller than 15 then it will issue an warning and provide references mentioning why the length should be at least  15.
