### ISSUE TITLE
Extracting model summary 

### ISSUE THREAD

**Issue by Farshad171** [USGS-R/EGRET#253]
In "loadflex" and "loadest", I am able to extract model summary. Is there a function to simply extract the summary (below example from loadflex) after running WRTDS and modelEstimation?
Thanks
Example from loadflex:
Station: SSR, TN
Constituent: TN

An object of class "compModel"
Slot "reg.model":
loadModel (subclass loadReg2)
***fit***
*** Load Estimation ***

Station: SSR, TN
Constituent: TN

Number of Observations: 73
Number of Uncensored Observations: 73
Center of Decimal Time: 2013.161
Center of ln(Q): 6.0154
Period of record: 2011-05-25 to 2014-12-15

Selected Load Model:
--------------------

TN ~ model(9)

Model coefficients:
            Estimate Std. Error z-score p-value
(Intercept) 10.26200    0.10710 95.8176  0.0000
lnQ          1.12697    0.07558 14.9107  0.0000
lnQ2         0.04090    0.04531  0.9026  0.3439
DECTIME      0.02221    0.03116  0.7129  0.4543
DECTIME2    -0.05219    0.03311 -1.5763  0.1005
sin.DECTIME  0.34615    0.05386  6.4273  0.0000
cos.DECTIME  0.43961    0.10991  3.9998  0.0001

AMLE Regression Statistics
Residual variance: 0.07419
R-squared: 92.64 percent
G-squared: 190.4 on 6 degrees of freedom
P-value: <0.0001
Prob. Plot Corr. Coeff. (PPCC):
r = 0.9751
p-value = 0.0081
Serial Correlation of Residuals: 0.095

Variance Inflation Factors:
              VIF
lnQ         4.991
lnQ2        1.782
DECTIME     1.101
DECTIME2    1.104
sin.DECTIME 1.157
cos.DECTIME 5.488

Comparison of Observed and Estimated Loads
------------------------------------------
      Summary Stats: Loads in kg/d
---------------------------------------------
     Min  25%   50%   75%   90%   95%    Max
Est 4710 9110 12600 33400 67300 98400 261000
Obs 3690 8670 12100 30900 80000 94200 362000

Bias Diagnostics
----------------
 Bp: -1.431 percent
PLR: 0.9857
  E: 0.8767

**Comment by rmhirsch49** [comment]
There is no similar command in EGRET.  I simple description of the model really isn’t possible because the coefficients vary over time and over discharge.  However, there is one output that can show a number of features of the estimated model and that is fluxBiasMulti(eList).  This will produce graphics that are very informative about the model fit.  One thing we know we should also do in a future release is to provide some overall statistics about the model such as mean squared error and an equivalent of R-squared.  These can be computed fairly easily from the Sample data frame, but we haven’t provided a script for these things at this point.

Thanks for the question.

Bob Hirsch
