### ISSUE TITLE
Add 'concMin' argument to plotConcHist()

### ISSUE THREAD

**Issue by emorway-usgs** [USGS-R/EGRET#32]
There is a very subtle, seeming steady, possibly significant (statistically speaking) upward trend in pH (plot below).  It is difficult to detect, however, because the y-axis lower limit defaults to 0.  Would it be possible to add a concMin argument to plotConcHist(), kind of like what exists in plotConcQSmooth(eList, date1, date2, date3, qBottom, qTop, qUnit=1,  printLegend=FALSE, concMin=7)

![plotconchist](https://cloud.githubusercontent.com/assets/3236576/6087498/05e3fb44-ae01-11e4-9b18-dfa745ddc8dd.png)

**Comment by rmhirsch49** [comment]
Eric: you asked one of my favorite questions.  I very intentionally did not make it an option to pick any value for the minimum on the y axis of these plots.  When I was a young hydrologist at the USGS Walter Langbein told me that the vertical scale on a graph should always go to zero (unless you are working with logs). Anything else can be highly misleading.  

Now, I was generally thinking in terms of this variable being plotted being a concentration or a flux.  What you have here is pH, which is the negative base ten logarithm of the hydrogen ion concentration.  What you could do is transform your pH to a hydrogen ion concentration and graph that.  Might be kind of neat.  The other thing is that you could go into the code for plotConcHist and figure out how we made the y-axis go to zero and write it to go to some other number (like maybe 7).  That's the beauty of R, you can take are code and modify it to your liking.  

But, since most users will be doing concentrations I'm going to stick to my guns and make it hard to do anything but have the axis go to zero.

Bob Hirsch

**Comment by jread-usgs** [comment]
@rmhirsch49 what do you think about leaving this issue open and labeling it with the "wontfix" label? Since it is a common issue, this would let others know that it is a conscious decision and they can see the discussion here. 

I agree that it should be hard to deviate from a zero pinned y-axis, but I would argue that it shouldn't be impossible (maybe pass in `ylim = c(y1,y2)` through `...` in the function?) The reverse argument is true to misleading plots, i.e., a temperature trend in Kelvin would look very different than the same data in °C in EGRET. Should that be the case?

**Comment by ldecicco-USGS** [comment]
I am going to re-open this issue (for the moment at least) because I need to submit a fix to CRAN that allows users to see the 'sysdata.rda' data. These are the objects that EGRET uses to convert flux and flow units. Historically, they were open, but then other packages couldn't call EGRET functions. Using the hidden 'sysdata.rda' fixed that bug...but now users can't easily just poke around within the functions (it's a really weird behavior of R, I know). I have recently figured out a way to expose the 'hidden' data, so I need to submit a updated version to CRAN to make everyone happy.

Until that version is out, users might run into problems altering the EGRET functions. I expect this to submit a new release to CRAN sometime this week.

**Comment by rmhirsch49** [comment]
Just to be clear Jordan.  These plots are designed for concentrations or
fluxes.  I agree that my generalization doesn't work for temperature, just
like it doesn't work for pH.  So, I'm sticking with my position.

Bob

On Mon, Feb 9, 2015 at 9:37 AM, Jordan S Read <notifications@github.com>
wrote:

> @rmhirsch49 <https://github.com/rmhirsch49> what do you think about
> leaving this issue open and labeling it with the "wontfix" label? Since it
> is a common issue, this would let others know that it is a conscious
> decision and they can see the discussion here.
>
> I agree that it should be hard to deviate from a zero pinned y-axis, but I
> would argue that it shouldn't be impossible (maybe pass in ylim = c(y1,y2)
> through ... in the function?) The reverse argument is true to misleading
> plots, i.e., a temperature trend in Kelvin would look very different than
> the same data in °C in EGRET. Should that be the case?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-R/EGRET/issues/32#issuecomment-73518228>.
>



-- 

************************************************************
* Robert M. Hirsch
* Research Hydrologist
* 432 National Center                     rhirsch@usgs.gov
* U.S. Geological Survey                ph  703-648-5888
* Reston, VA 20192         http://profile.usgs.gov/rhirsch
*************************************************************

**Comment by jread-usgs** [comment]
ahh, gotcha. I thought your position was general to plots.

**Comment by mturtora-USGS** [comment]
If you want a good reference for this, there is a wonderful little book that I first saw in high school and that looks like it's still in print. I also just found a pdf online without even trying:

Huff (1954) How to lie with Statistics. WW Norton, NY.

This is a tongue-in-cheek look at how statistics are misused in the media and advertising.  Chapter 5 "The Gee-Whiz Graph" is devoted to this topic.  It gives an example of an advertiser being spoofed from 1938 (page 64 of the first edition) with the spoof headline, "Government Pay Rolls Stable."  Personally, I think everyone should read this book.

I think the exceptions to this rule of thumb are illuminating.  River stage comes to mind. Generally, I think it has to do with arbitrary scales and the degree of meaningful variation. The only absolute fixed reference for an elevation is the center of the earth but even using local maximum depth would obscure shoreline changes.

If fact, a couple of months ago, I modified the plotFlowSingle function to plotStageSingle and was trying to figure out this very issue.

So I changed this line:
yInfo <- generalAxis(x = qActual, maxVal = qMax, minVal = 0, 
to this line:
yInfo <- generalAxis(x = qActual, maxVal = qMax, minVal = qMin, 

And faked stage into the Q variable.  This mod sets the minimum y-axis value to the minimum stage.

Finally, an "honest" solution to show slight variations would be to plot the variation about the mean.  That equates to a residual plot of a linear model with only an intercept term.
