### ISSUE TITLE
Any recommendations on predicting future concentrations?

### ISSUE THREAD

**Issue by kqasem** [USGS-R/EGRET#331]
Hey,
Is there any library/tool within EGRET to predict future concentrations?

I have historical flow and total suspended sediment (TSS) data (1962 - 1975). I would like to use this data to predict TSS concentrations in 2020 and use it as a modeling upstream boundary condition.

My understanding is that since I don't have TSS data in 2020, I can't use the WRDTS tool. Do you have any recommendations?

Any suggestion is appreciated!
Karoline

![image](https://user-images.githubusercontent.com/36547773/139963396-e55f4e60-1940-4ebd-8f59-543b89abcdbb.png)

**Comment by rmhirsch49** [comment]
Karoline:  The fundamental question that you would need to answer before attempting what you mention is this:  Do you believe that the Conestoga watershed’s “behavior” with respect to TSS in 2020 is likely to be fairly similar to what it was in 1975.  By “behavior” I mean what level of TSS concentration we can expect for a given flow on a given day of the year.  I know something about the Conestoga watershed and know that major efforts have been underway there to reduce many forms of non-point source pollution (of which TSS would be a part) and thus using a WRTDS model calibrated to 1962-1975 conditions couldn’t really be justified.  If this was a case where the model was built on data up through 2019 (for example) there are ways to use WRTDS to explore what 2020 TSS concentrations might look like.  (Doing that would require some special programming, but are not impossible).

In general, WRTDS is not intended to extrapolate water quality over time, because it doesn’t build on any sort of model of the causative mechanisms related to land use, BMPs, etc. built into it.  Rather, it is an interpolation tool, designed to infer reasonable estimates of concentrations for the many days during the period of monitoring that were not sampled.  The software does make it possible to extend slightly past the end of the water quality record, but that is just for purposes of making estimates for the final year or water year of the record.  Attempts to extrapolate a WRTDS model beyond a few months is not a good idea at all, because the mathematics is such that concentration versus discharge relationships can become highly unrealistic and highly sensitive to the last few samples collected.

I’d be happy to discuss this more, if you want to direct an e-mail to me directly.  I would be glad to pursue your issue to try to find an approach that meets your needs, but I don’t want to fill up this listserve with those discussions.

Robert Hirsch.   ***@***.***

From: Karoline Qasem ***@***.***>
Date: Tuesday, November 2, 2021 at 7:01 PM
To: USGS-R/EGRET ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [USGS-R/EGRET] Any recommendations on predicting future concentrations? (Issue #331)



 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hey,
Is there any library/tool within EGRET to predict future concentrations?

I have historical flow and total suspended sediment (TSS) data (1962 - 1975). I would like to use this data to predict TSS concentrations in 2020 and use it as a modeling upstream boundary condition.

My understanding is that since I don't have TSS data in 2020, I can't use the WRDTS tool. Do you have any recommendations?

Any suggestion is appreciated!
Karoline

[image]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F36547773%2F139963396-e55f4e60-1940-4ebd-8f59-543b89abcdbb.png&data=04%7C01%7Crhirsch%40usgs.gov%7C51f5832073494026a2c208d99e54b0d6%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637714908855209143%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Ew0ijy9Xc%2FBwsJ5N5hg0r3MFQAbqHDOwhpuHSWWsVio%3D&reserved=0>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUSGS-R%2FEGRET%2Fissues%2F331&data=04%7C01%7Crhirsch%40usgs.gov%7C51f5832073494026a2c208d99e54b0d6%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637714908855219099%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=RM3nDOjX0jgpN7SEvLU6ft2tYUN0zTS1ZOVD6TgnvNo%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAI53UITEC5RYNNPWLMUKPDUKB3T3ANCNFSM5HHS4QQQ&data=04%7C01%7Crhirsch%40usgs.gov%7C51f5832073494026a2c208d99e54b0d6%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637714908855219099%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NU62p6B%2FPPp7J3SowHIcJRUHfzL5VGCxDGICZEYllC4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crhirsch%40usgs.gov%7C51f5832073494026a2c208d99e54b0d6%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637714908855229053%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gQ%2Fwwn4LTplvtJrmY2aJzTETd%2Fbu%2F0qRjzNLyL9WRv0%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crhirsch%40usgs.gov%7C51f5832073494026a2c208d99e54b0d6%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637714908855229053%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JSD%2FhKwwhrPx362P2ltRwNwHKvpEAMKAYcBOdTRm2DM%3D&reserved=0>.
