### ISSUE TITLE
fluxUnit suggestion

### ISSUE THREAD

**Issue by emorway-usgs** [USGS-R/EGRET#36]
For your customers with native data units in ng/L, it would be helpful to have a fluxUnit option of kg/yr.  After pulling the data from NWIS, I do the recommended conversion of:

Sample$ConcLow <- Sample$ConcLow / 1000000
Sample$ConcHigh <- Sample$ConcHigh / 1000000
Sample$ConcAve <- Sample$ConcAve / 1000000

to get the data into the expected units of mg/L.  After progression through the WRTDS workflow and running tableChange(), I ignore the warning message at the end of the screen output regarding units of ng/L in INFO, but am hopeful that a units value for these smaller annual fluxes could be provided?  If you would prefer users do the conversion themselves, no problem, only a suggestion.  

tableChange(eList, fluxUnit=8, yearPoints=c(1998,2005,2013))

...
                 Flux Trends
  time span          change        slope       change        slope
                  10^3 kg/yr    10^3 kg/yr /yr      %         %/yr
 1998  to  2005      0.00076      0.00011           10          1.5
 1998  to  2013       0.0052      0.00035           70          4.7
 2005  to  2013       0.0044      0.00055           54          6.8

or changing fluxUnit=3 yields

tableChange(eList, fluxUnit=8, yearPoints=c(1998,2005,2013))
...
                 Flux Trends
   time span          change        slope       change        slope
                   kg/day       kg/day   /yr      %         %/yr
 1998  to  2005       0.0021        3e-04           10          1.5
 1998  to  2013        0.014      0.00095           70          4.7
 2005  to  2013        0.012       0.0015           54          6.8

**Comment by ldecicco-USGS** [comment]
Sounds reasonable to me. I'm just cleaning up the helpfiles for the #24 . Adding kg/yr should be simple enough.

**Comment by ldecicco-USGS** [comment]
Added to the latest Pull Request.

**Comment by rmhirsch49** [comment]
Laura:  I agree, that broadening our range of units would be good.  While
you are at it, we should probably add lbs per year as well.

I think it would be nice to have a something available to users who have
issues of these very low concentration levels to help them work their way
through the process. In working with Eric's data I hated the fact that once
I converted to mg/L then any graph of concentration looked terrible because
there were so many zeros after the decimal point.

Thanks.  Bob

On Tue, Feb 10, 2015 at 4:19 PM, Laura DeCicco <notifications@github.com>
wrote:

> Added to the latest Pull Request.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-R/EGRET/issues/36#issuecomment-73785729>.
>



-- 

************************************************************
* Robert M. Hirsch
* Research Hydrologist
* 432 National Center                     rhirsch@usgs.gov
* U.S. Geological Survey                ph  703-648-5888
* Reston, VA 20192         http://profile.usgs.gov/rhirsch
*************************************************************

**Comment by ldecicco-USGS** [comment]
Added kg/yr. Should be on CRAN now...might take awhile to trickle down to mirrors.
