### ISSUE TITLE
Add qUnit argument to plot15

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/EGRET#40]
Would like to see the `plot15` function in units other than mm/day.

**Comment by rmhirsch49** [comment]
I can't think of a strong reason not to do it.  It may be that we just did it that way because that's how I origninally programmed it for the Rick and Hirsch paper.  One concern I'd have is that space is very tight in this figure and going to some other discharge units might cause the length of the y-axis label to get to be too long.  Runoff in mm/year is nice and short.  I guess I'd say give it a try, but I don't see it as a high priority.
