### ISSUE TITLE
How to handle a concentration of zero

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/EGRET#50]
`modelEstimtion` fails if there is a measurement that claims 0 in the concMin and concMax columns.

We could just check, if there are 0's in concAve, and error out with a useful message, leaving the process of what to do up to the user (ie, drop the rows? insert an artificial detection level? something else?)

**Comment by rmhirsch49** [comment]
I think you mean "claims 0 in the ConcLow and ConcHigh columuns" -- I think a check is a good idea, but I wouldn't use ConcAve (because it actually doesn't come into play at all in modelEstimation).  I think that I'd say that the test should be, if there is 1 or more 0 value in ConcLow and/or 1 or more 0 value in ConcHigh, then the warning should come up and modelEstimation shouldn't be run.  I think that what we need to tell the user is that if they can surmise what the correct reporting level should be, they can use the function fixSampleFrame to take care of the problem.  They can see the help page for fixSampleFrame to get an idea of how to do this.  It is also discussed in the User Guide.
